# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28452dc8694f053af4e4df6769e156438f8df28cb73c05e4a68e4394fcf77f0c92f4f05848b8061b1aa6f2ac8e40e6fbf64c3e10aeea6900ceaaadaae3701ee8

test:
  secret_key_base: 9e24bb8801ddf49e2d4e5da34512e970f1044d127aceba74ee0f7b52ecba4a201f471771530ebc959d877a9ad0103bdf0814b4a929992fd4ea9afd9315ca711f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
